# Generated by Django 6.0.2 on 2026-02-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kran_typ', models.CharField(max_length=50)),
                ('fabrik_nr', models.CharField(max_length=50)),
                ('kunde', models.CharField(max_length=255)),
                ('lg', models.CharField(blank=True, max_length=50, null=True)),
                ('kundenummer', models.CharField(blank=True, max_length=50, null=True)),
                ('version', models.CharField(max_length=20)),
                ('serien_nr', models.CharField(max_length=50)),
                ('tel_nr', models.CharField(max_length=50)),
                ('ip_rueckmeldung', models.CharField(max_length=100)),
                ('it_nr', models.CharField(max_length=50)),
                ('kundenkran_miete', models.CharField(max_length=50)),
                ('lizenz_janein', models.CharField(max_length=10)),
                ('lizenzdatum', models.CharField(max_length=20)),
                ('bezahlt_bis', models.CharField(max_length=20)),
                ('rg_erstellt', models.CharField(max_length=20)),
                ('servicemeldung', models.IntegerField()),
            ],
        ),
    ]
