# Generated by Django 6.0.2 on 2026-02-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crane',
            name='it_nr',
            field=models.CharField(max_length=20),
        ),
    ]
