# Generated by Django 6.0.2 on 2026-02-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_departmentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='crane',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
