# Generated by Django 6.0.2 on 2026-03-04 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_craneduetracking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentData',
        ),
    ]
